pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016

variables:
  - group: Application_var

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in dbCred.py'
  inputs:
    targetFiles: '**/dbCred.py'
    tokenPrefix: '__'
    tokenSuffix: '__'
- task: SonarCloudAnalyze@1
  displayName: 'sonar'

